use_frameworks!

target 'PazMoPubBannerViewController_Example' do
  pod 'PazMoPubBannerViewController', :path => '../'

  target 'PazMoPubBannerViewController_Tests' do
    inherit! :search_paths

    
  end
end
